### ISSUE TITLE
The ES5 example doesn't work as is

### ISSUE THREAD

**Issue by tehnomaag** [gcanti/tcomb-react#12]
The current ES5 example is:

```
propTypes: propTypes({
    name: t.Str,
    surname: t.maybe(t.Str),
    age: t.Num,
    gender: Gender,
    avatar: URL
  }),
```

But that throws a `TypeError: Cannot read property 'kind' of undefined` error inside `propTypes` call, since `propTypes` expects a tcomb type as its parameter.

Quick fix is to wrap the parameter object in `t.struct`, but it would be nice if `propTypes` itself did that just like the ES7 decorator does internally.

**Comment by gcanti** [comment]
Oh thanks, I agree. I'll fix that asap
