### ISSUE TITLE
Consider supporting any React versions by parameterizing React lib

### ISSUE THREAD

**Issue by zaim** [gcanti/tcomb-react#17]
Hi.

Since tcomb-react is using a very small (and stable?) subset of the React API (only `ReactElement` and `ReactNode`), it might be preferable to *not* have a hard dependency on React and a specific version.

Instead, create the `t.React*` types dynamically by accepting a `React` object.

Usage would be something like:

```javascript
import React from 'react'
import { props, t } from 'tcomb-react'

t.ReactElement // undefined

t.addReactTypes(React)

@props({
  children: t.ReactElement // ok!
})
class MyComponent extends React.Component {

  render() {
    return (
      <div>
        {this.props.children}
      </div>
    );
  }

}
```

This might be a breaking change since `t.React*` types won't be available at first import.

Another approach is to wrap your `require('react')` with a `try catch`.

Or is this too complicated? It's just that I wanted to try this with React 0.14.0-rc1 but cant... :)

**Comment by gcanti** [comment]
Hi @zaim,
Actually tcomb-react should be compatible with react@0.14.0-rc1 as the only API used is `React.isValidElement` (`ReactElement` and `ReactNode` are tcomb types).

**Comment by zaim** [comment]
Hmmm... I'm still getting 2 copies of React in node_modules, that is:

1. The "main" `node_modules/react` (0.14.0-rc1)
2. The one tcomb-react uses, `node_modules/tcomb-react/node_modules/react` (0.13.3)

Browserifying would include *both* copies, I think.

I think it's because `0.14.0-rc1` (anything with `-prerelease`) does not satisfy  `>=0.13.0` which is what's in your package.json.

So basically, my suggestion would make tcomb-react compatible with *any* and *every* future React releases, including pre-releases (as long as `React.isValidElement` is not deprecated :wink:)

**Comment by gcanti** [comment]
> my suggestion would make tcomb-react compatible with any and every future React releases, including pre-releases (as long as React.isValidElement is not deprecated :wink:)

Indeed, I thought that >=0.13.0 would be enough but it doesn't work with release candidates.
Related https://github.com/npm/npm/issues/8854

**Comment by gcanti** [comment]
Closing as per React v0.14
