### ISSUE TITLE
Add t.ReactChildren to pre-defined types

### ISSUE THREAD

**Issue by jedmao** [gcanti/tcomb-react#19]
In lieu of #18 it seems useful to include `t.ReactChildren` as a pre-defined type. Would you be willing to accept a PR with this inclusion?

**Comment by jedmao** [comment]
Also, I think it may be necessary to include `t.ReactNode` here, for cases when the children are a single `TextNode`. For example:

```jsx
<FooComponent>
    Hello, World!
</FooComponent>
```
So the final type would be:

```js
export const ReactChildren = t.union([
    t.Nil,
    t.ReactNode,
    t.ReactElement,
    t.list(t.ReactElement)
]);
```
How does that sound?

**Comment by gcanti** [comment]
Hi, 
Sorry for the delay.

Isn't `ReactNode` enough for your use case?

```js
import React from 'react';
import ReactDOM from 'react-dom';
import {t, props, ReactNode} from 'tcomb-react'

@props({
  children: t.maybe(ReactNode)
})
class A extends React.Component {
  render() {
    return <div>hello</div>;
  }
}

const mountNode = document.querySelector('#app')

ReactDOM.render(<A />, mountNode); // => ok
ReactDOM.render(<A><div/></A>, mountNode); // => ok
ReactDOM.render(<A><div/><div/></A>, mountNode); // => ok
ReactDOM.render(<A>world</A>, mountNode); // => ok
ReactDOM.render(<A>{null}</A>, mountNode); // => ok
ReactDOM.render(<A><div>{null}</div></A>, mountNode); // => ok
ReactDOM.render(<A><div/>{null}</A>, mountNode); // => KO!
```

**Comment by jedmao** [comment]
That appears to be working for now. I'll reopen if it presents itself again. Thanks!

**Comment by jedmao** [comment]
@gcanti it looks like this fails when you return `false` and I presume `undefined` in `children`. For example:

```jsx
<Foo>
    {isBar && (
        <div>baz</div>
    )}
</Foo>
```
If `isBar` is `false` then `t.maybe(t.ReactNode)` fails with:

> Invalid value false supplied to ReactNode.

However, if I don't use `tcomb` here then React gracefully displays nothing for `false` values.

I think `ReactChildren` might be better described as:

```jsx
const ReactChild = t.union([
  t.ReactNode,
  t.Boolean,
  t.Nil
]);

const ReactChildren = t.union([
  ReactChild,
  t.list(ReactChild)
]);
```

What do you think?

**Comment by gcanti** [comment]
Released in https://github.com/gcanti/tcomb-react/releases/tag/v0.8.10
