### ISSUE TITLE
add t.ReactClass

### ISSUE THREAD

**Issue by FrancescoCioria** [gcanti/tcomb-react#26]
I think we should add a way to verify if a `prop` is a valid `ReactClass`. This is useful (for example) in case your component accepts a replacement to use as wrapper element:

```jsx
@props({
  component: t.maybe(t.union([ ReactClass, t.String ]))
  ...
})
class MyWrapper extends React.Component {

  static defaultProps = { component: 'div' }
  {...}
  template({ component, children, props }) {
    return React.createElement(
      component,
      props,
      children
    );
  }

}
```

FYI: In my application I defined `ReactClass` as
```js
t.irreducible('ReactClass', x => x && x.prototype && (x.prototype instanceof React.Component || t.Function.is(x.prototype.render)));
```

NOTE: `x.prototype instanceof React.Component` is unnecessary, but when (if) you drop support for classes defined with `React.createClass` it will become, I think, the only necessary check

**Comment by gcanti** [comment]
Hi @FrancescoCioria,

I see a problem though, you are ruling out stateless components defined with simple functions:

```js
import t from 'tcomb'
import React from 'react'


const A = React.createClass({
  render() {
    return <div/>
  }
})

class B extends React.Component {
  render() {
    return <div/>
  }
}

function C() {
  return <div/>
}

const ReactClass = t.irreducible('ReactClass', x => x && x.prototype && (x.prototype instanceof React.Component || t.Function.is(x.prototype.render)));

console.log(ReactClass.is(A)) // => true
console.log(ReactClass.is(B)) // => true
console.log(ReactClass.is(C)) // => false, ouch!
```

**Comment by FrancescoCioria** [comment]
Mmm, you're right, but actually I don't see it as a big problem as stateless components are not fully functional `ReactClass`es: they're never instantiated and don't have lifecycle methods.

If you want to consider stateless components as a `ReactClass` than any function could be a `ReactClass` (unless you verify it actually return a `t.ReactNode`).

I suggest to separate standard classes from stateless components and not consider the last one as a `ReactClass`, but this is my opinion :)

**Comment by gcanti** [comment]
> If you want to consider stateless components as a `ReactClass`...

Actually I don't know what a *ReactClass* is, you didn't provide a definition. If, for example, a ReactClass is "a model or a shape for components", then stateless components are legit and to exclude them seems arbitrary.

My previous objection regards your own use case, where stateless components fit perfectly:

```js
@props({
  component: t.maybe(t.union([ t.Function, t.String ])),
  children: t.Any
})
class MyWrapper extends React.Component {

  static defaultProps = { component: 'div' }

  render() {
    return React.createElement(
      this.props.component,
      this.props,
      this.props.children
    )
  }

}

function Strong(props) {
  return <strong>{props.children}</strong>
}

render(<MyWrapper component={Strong}>Hello</MyWrapper>, document.getElementById('app'))
```

**Comment by FrancescoCioria** [comment]
do you think it would be possible to identify a stateless component and distinguish it from a general `Function`?

as described [here](https://facebook.github.io/react/docs/reusable-components.html#stateless-functions) a *Stateless Function* accepts one argument (`props: t.Object`) and should return a valid `t.ReactNode`.

maybe we could do something like this:
```js
t.irreducible('StatelessFunction', x => t.func({}, t.ReactNode)
```

and then:
```js
t.irreducible('ReactClass', x => x && (t.StatelessFunction.is(x) || (x.prototype && (x.prototype instanceof React.Component || t.Function.is(x.prototype.render)));
```

what do you think?

**Comment by gcanti** [comment]
> a Stateless Function accepts one argument (props: t.Object) and should return a valid t.ReactNode

Actually should return a valid **`t.ReactElement`**. Returning a `t.ReactNode` (or `null` or `false`) is not legal:

```js
function C() {
  return <div>hello</div> // a ReactElement
}

render(<C />, document.getElementById('app')) // => ok

function D() {
  return 'hello' // a ReactNode
}

render(<D />, document.getElementById('app')) // => throws Warning: D(...): No `render` method found on the returned component instance: you may have forgotten to define `render`, returned null/false from a stateless component, or tried to render an element whose type is a function that isn't a React component.
```

The example above shows that React v0.14.x already does a runtime check to ensure that a stateless function returns a valid `ReactElement`, duplicating such check using a `tcomb`'s type is useless. 

Hence the type of a stateless component can be just `t.Function`. 

However, all `A`, `B`, `C` are functions:

```js
console.log(t.Function.is(A)) // => true (createClass)
console.log(t.Function.is(B)) // => true (ES6 class)
console.log(t.Function.is(C)) // => true (stateless component)
```

thus your predicate is redundant:

```js
x => x && (t.Function.is(x) || (x.prototype && (x.prototype instanceof React.Component || t.Function.is(x.prototype.render))
```

being equivalent to `t.Function.is` and this finally leads to my typing for your use case: `union([t.String, t.Function])`

**Comment by FrancescoCioria** [comment]
> The example above shows that React v0.14.x already does a runtime check to ensure that a stateless function returns a valid `ReactElement`, duplicating such check using a `tcomb`'s type is useless.

I agree

> this finally leads to my typing for your use case: `union([t.String, t.Function])`

Yes, this was actually my starting point, I hoped I could improve it somehow, but I'm afraid didn't count *Stateless Functions*

 Thanks for your help and the clear explanations!
