### ISSUE TITLE
`t.ReactChildren` rejects a correctly renderable `children`

### ISSUE THREAD

**Issue by FrancescoCioria** [gcanti/tcomb-react#29]
## bug-report
`t.ReactChildren` rejects an `Array` of `Arrays` if the last one has one or more `t.Nil`s

## how to reproduce
```js
t.ReactChildren.is([ 'hello', [ 'world' ] ]) // ok
t.ReactChildren.is([ 'hello', [ null ] ]) // rejected!
```

## probable cause
this precise problem is caused by `t.ReactChildren` being recursive with `t.ReactChild` instead of itself (https://github.com/gcanti/tcomb-react/blob/master/index.js#L135):

```js
ReactChildren = t.irreducible('ReactChildren', function(x) {
  return ReactChild.is(x) || t.list(ReactChild).is(x); // (shouldn't this be t.ReactChildren?)
});
```

**Comment by gcanti** [comment]
Hi @FrancescoCioria,

Thanks for reporting.

> shouldn't this be t.ReactChildren?

Looks good to me. Would you like to send a PR?

**Comment by FrancescoCioria** [comment]
@gcanti done. see #30

**Comment by gcanti** [comment]
Released in https://github.com/gcanti/tcomb-react/releases/tag/v0.8.13
