### ISSUE TITLE
Document what this compiles to

### ISSUE THREAD

**Issue by rattrayalex** [gcanti/tcomb-react#34]
Hi there, 

This looks like an amazing tool! I'd be curious whether it compiles to `MyComponent.propTypes = {...}` or not, and what kind of output a custom type might produce. Could this be documented in the readme?

Thanks!

**Comment by gcanti** [comment]
> I'd be curious whether it compiles to MyComponent.propTypes

It does. As you can see in the [source code](https://github.com/gcanti/tcomb-react/blob/master/index.js#L38) every type is compiled to a [custom prop validator](http://facebook.github.io/react/docs/reusable-components.html)

> what kind of output a custom type might produce

Not sure I understand, could you please show an example?

**Comment by rattrayalex** [comment]
You bet, sorry for being unclear. What I'd love to see in the Readme is: 

```js
import t from 'tcomb'
import { props } from 'tcomb-react'

const Gender = t.enums.of(['Male', 'Female'], 'Gender')
const URL = t.refinement(t.String, (s) => s.startsWith('http'), 'URL')

@props({
  name: t.String,             // a required string
  surname: t.maybe(t.String), // an optional string
  age: t.Number,              // a required number
  gender: Gender,             // an enum
  avatar: URL                 // a refinement
})
class Card extends React.Component {

  render() {
    return (
      <div>
        <p>{this.props.name}</p>
        ...
      </div>
    )
  }

}


// compiles to...
class Card extends React.Component {

  render() {
    return (
      <div>
        <p>{this.props.name}</p>
        ...
      </div>
    )
  }
}
Card.propTypes = {
  name: React.PropTypes.string.isRequired,
  surname: React.PropTypes.string,
  age: React.PropTypes.number,
  gender: ???
  avatar: ???
};
```
... or whatever it does, in fact, compile to 😄

**Comment by rattrayalex** [comment]
Ah, sorry, missed the source code link. I see how it works. Nice. Hmm not sure how best to explain that then.

**Comment by gcanti** [comment]
> Hmm not sure how best to explain that then

Eh.. yes, it's not so easy 'cause propTypes are functions generated on the fly

**Comment by rattrayalex** [comment]
Hmm, maybe something like this:


The `@props` decorator sets `propTypes` on the target component to use a [custom validator function](https://facebook.github.io/react/docs/reusable-components.html#prop-validation) built around tcomb types for each specified prop. 

Thus, the following:

```js
const URL = t.refinement(t.String, (s) => s.startsWith('http'), 'URL');

@props({
  name: t.String,
  url: URL,
})
class MyComponent extends React.Component {
  // ...
}
```
becomes something along the lines of:
```js
const URL = t.refinement(t.String, (s) => s.startsWith('http'), 'URL');

class MyComponent extends React.Component {
  // ...
}
MyComponent.propTypes = {
  name: function(props, propName, componentName) {
     if (!t.validate(props[propName], t.string)) {
       return new Error('...');
     }
  },
  url: function(props, propName, componentName) {
     if (!t.validate(props[propName], URL)) {
       return new Error('...');
     }
  },
}

**Comment by rattrayalex** [comment]
By the way, thanks very much for your quick and thoughtful responses!

**Comment by gcanti** [comment]
Looks good, thanks. Would you like to send a PR?

Some nitpicks:

```js
const URL = t.refinement(t.String, (s) => s.startsWith('http'), 'URL');

class MyComponent extends React.Component {
  // ...
}
MyComponent.propTypes = {
  name: function(props, propName, componentName) {
     if (!t.validate(props[propName], t.String).isValid()) { // <= t.String instead of t.string and isValid() call
       return new Error('...');
     }
  },
  url: function(props, propName, componentName) {
     if (!t.validate(props[propName], URL).isValid()) {
       return new Error('...');
     }
  },
}
```

**Comment by rattrayalex** [comment]
Sure, happily! Thanks for the nits – good catch
