### ISSUE TITLE
Document usage with flow in Readme

### ISSUE THREAD

**Issue by rattrayalex** [gcanti/tcomb-react#35]
Hi, 

The example on the [babel-plugin-tcomb](https://github.com/gcanti/babel-plugin-tcomb#type-checking-react) page with flow types used for props was quite enticing: 

```js
import { props } from 'tcomb-react'

type Props = {
  name: string
};

@props(Props)
class Hello extends React.Component<void, Props, void> {
```

It might be helpful to include a similar piece of documentation on the Readme of this project, as the Flow shorthand is more clearly a convenience win than raw tcomb (which has its own benefits)

**Comment by gcanti** [comment]
Just added a new section, thanks for the suggestion
