### ISSUE TITLE
What is the recommended way to transfer props to an underlying HTML element?

### ISSUE THREAD

**Issue by jedmao** [gcanti/tcomb-react#38]
For example, say you want a component that renders a div and you want to allow any props that would normally be accepted for a div.

I'm trying to avoid the following:
```jsx
    propTypes: propTypes(t.struct({
        divProps: t.Any,
        children: t.ReactChildren
    })),

    render() {
        const { divProps, children } = this.props;
        return (
            <div {...divProps}>
                {children}
            </div>
        );
    },
```
I'd also like to avoid the following:

```jsx
    propTypes: propTypes(t.struct({
        children: t.ReactChildren
    }), { strict: false }),

    render() {
        return (<div {...this.props} />);
    },
```
Would this, perhaps, require a separate tcomb library that does not yet exist, like `tcomb-html` or `tcomb-dom`? This way, you could do something like:
```jsx
    propTypes: propTypes(t.struct({
        divProps: tdom.DivProps,
        children: t.ReactChildren
    })),

    render() {
        const { divProps, children } = this.props;
        return (
            <div {...divProps}>
                {children}
            </div>
        );
    },
```
In this case, the `DivProps` would be a sub-type of [`GlobalAttributes`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes).

See also: [React: Transferring Props: A Shortcut](https://facebook.github.io/react/docs/reusable-components.html#transferring-props-a-shortcut).

**Comment by gcanti** [comment]
> I'm trying to avoid the following:

```js
propTypes: propTypes(t.struct({
    divProps: t.Any,
    children: t.ReactChildren
})),

render() {
    const { divProps, children } = this.props;
    return (
        <div {...divProps}>
            {children}
        </div>
    );
},
```

Why not? AFAIK React v15.0.2 is already checking for invalid attributes

**Comment by jedmao** [comment]
That's a good point.
