### ISSUE TITLE
Intersections props

### ISSUE THREAD

**Issue by singggum3b** [gcanti/tcomb-react#40]
Hi! Does this use case supported?
```
export type QAThreadParamsType = {
	id: string | number
} | {
	params: {
		id: string | number
	}
}

export type QAThreadPropsType = {
	eventStore?: Object,
	store: Object,
	dispatch: Function,
	__statePath: Array<string>,
} & QAThreadParamsType
```

Currently it throwing, because it can't access props of intersection type

**Comment by gcanti** [comment]
*Who* is throwing? I see only flow types. Please post reproduction steps

**Comment by singggum3b** [comment]
Sorry for the unclear question :sob: 
I'm trying to use tcomb-react, guess this's the edge case: 
```
export type QAThreadParamsType = {
    id: string | number
} | {
    params: {
        id: string | number
    }
}

export type QAThreadPropsType = {
    eventStore?: Object,
    store: Object,
    dispatch: Function,
    __statePath: Array<string>,
} & QAThreadParamsType

@props(QAThreadPropsType,{strict: false})
export default class QAThread extends React.Component {..}
```
Error: 
```
Cannot convert undefined or null to object
```

**Comment by gcanti** [comment]
Ak ok, so from the code you posted I guess you are using `babel-plugin-tcomb` to translate flow types to tcomb types and then pass them to the `props` decorator.

Intersections are not supported (nor unions) at the moment.

However I think they could be supported

**Comment by singggum3b** [comment]
It would be great if intersection & union is supported. :+1:

**Comment by gcanti** [comment]
You can try the new feature uninstalling your local copy of `tcomb-react` and installing `npm install gcanti/tcomb-react#40`. If everything's ok I'll publish a new release

**Comment by singggum3b** [comment]
Thanks, i'll try it tonight after work and let you know the result

**Comment by singggum3b** [comment]
Hey, i just tested the branch #40 and it worked, but the if the props is invalid , the error throwed is not really debug friendly. It print out the whole props , instead of pointing out which props was missing or invalid.

**Comment by gcanti** [comment]
This is what I get running the following

```js
import React from 'react'
import { props } from 'tcomb-react'

export type QAThreadParamsType = {
    id: string | number
} | {
    params: {
        id: string | number
    }
};

export type QAThreadPropsType = {
    eventStore?: Object,
    store: Object,
    dispatch: Function,
    __statePath: Array<string>,
} & QAThreadParamsType;

@props(QAThreadPropsType)
export default class QAThread extends React.Component {}

<QAThread />
```

<img width="715" alt="screen shot 2016-08-29 at 18 53 43" src="https://cloud.githubusercontent.com/assets/878912/18059605/0695aab2-6e1a-11e6-9554-d4a903b72acc.png">

**Comment by singggum3b** [comment]
Try the case with valid value in `QAThreadPropsType` but invalid value in `QAThreadParamsType`.

**Comment by gcanti** [comment]
It's expected, since `QAThreadParamsType` is a union and tcomb-react doesn't know which type should be selected

**Comment by singggum3b** [comment]
What can i do to improve the debug logging?

**Comment by gcanti** [comment]
Well, it depends on how you want to improve the error messages, without a spec is hard to tell. 

My advice is to split this issue in 2: now we have a working version which doesn't throw and can be released right away. After that you can work on improving the error messages (if needed)

**Comment by singggum3b** [comment]
Yes , i think this can be released already.
About the error message, i was thinking some thing along the line:
```
(data) -> [A | B]: throw error the same as  (data)-> A ; (data) -> B , if both are invalid
```
Basically when error occur, try to check the data with each type in the union to get the simpler error message.
Is that reasonable?

**Comment by gcanti** [comment]
ok going to merge and release. For the error message I guess it's a `tcomb-validation` enhancement

**Comment by gcanti** [comment]
Released in https://github.com/gcanti/tcomb-react/releases/tag/v0.9.3
