### ISSUE TITLE
union of array of struct will not work.

### ISSUE THREAD

**Issue by xpol** [gcanti/tcomb-react#52]
```js
class Test extends Component {
  static propTypes = propTypes({
     test: t.union([
      t.Function,
      t.list(t.struct({
        a: t.String
      }))])
  })
  //...
}
```

and Then use

```jsx
<Test test={[{a: 'a'}]} />
```

Will got:

> Warning: Failed prop type: [tcomb] Invalid prop "test" supplied to Test, should be a Function | Array<Struct{a: String}>.
>
> Detected errors (1):
>
>  1. Invalid value [
>   {
>     "a": "a"
>   }
> ] supplied to Function | Array<Struct{a: String}>

Also throws error like above in the follow case:

```js
  t.union([
      t.list(t.struct({
        a: t.String
      })),
      t.Function
  ])
```

```js
  t.union([
      t.String,
      t.list(t.struct({
        a: t.String
      }))
  ])
```

**Comment by gcanti** [comment]
Please try using `t.interface` instead of `t.struct`

```js
t.union([
      t.Function,
      t.list(t.interface({
        a: t.String
      }))])
```      

should work as expected

**Comment by xpol** [comment]
Yes, it works with interface.

Thank you very much!
